# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Perfops < Formula
  desc ""
  homepage "https://github.com/ProspectOne/perfops-cli"
  version "0.8.16"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ProspectOne/perfops-cli/releases/download/v0.8.16/perfops-cli_0.8.16_Darwin_arm64.tar.gz"
      sha256 "6c8fa0402cc7c2f9e2c3920e289d15813733b86bd98f48323b731008d903f5f5"

      def install
        bin.install "perfops"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ProspectOne/perfops-cli/releases/download/v0.8.16/perfops-cli_0.8.16_Darwin_x86_64.tar.gz"
      sha256 "4cac5e7adbe47532962ee45717b40e4c96815a22629ddba47c15217a0b04fcea"

      def install
        bin.install "perfops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ProspectOne/perfops-cli/releases/download/v0.8.16/perfops-cli_0.8.16_Linux_x86_64.tar.gz"
      sha256 "b8e48f557be5c57797e3a3014cd395470b5e0728fb323e55ae3d6972259567a9"

      def install
        bin.install "perfops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ProspectOne/perfops-cli/releases/download/v0.8.16/perfops-cli_0.8.16_Linux_arm64.tar.gz"
      sha256 "ba293bc36b2de90718740d52f3c269a9f336d6c916b7f4ccf4c4328f01ae667a"

      def install
        bin.install "perfops"
      end
    end
  end
end
