# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Perfops < Formula
  desc ""
  homepage "https://github.com/ProspectOne/perfops-cli"
  version "0.8.8"

  on_macos do
    url "https://github.com/ProspectOne/perfops-cli/releases/download/v0.8.8/perfops-cli_0.8.8_Darwin_all.tar.gz"
    sha256 "2a62eb2323cf6d51fc53fc6c34d253021928376f5c5ce1654f2dfbfce1988392"

    def install
      bin.install "perfops"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ProspectOne/perfops-cli/releases/download/v0.8.8/perfops-cli_0.8.8_Linux_arm64.tar.gz"
      sha256 "7b467d6ba1ddb760d4b5400ba4f46114f41803d2f7181248cb330da7a5513325"

      def install
        bin.install "perfops"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ProspectOne/perfops-cli/releases/download/v0.8.8/perfops-cli_0.8.8_Linux_x86_64.tar.gz"
      sha256 "81b55cec2afdd438d0a324fa8a6ba450f0826055bfb8a90ccdb27f8533470794"

      def install
        bin.install "perfops"
      end
    end
  end
end
